# Наследуем тему keycloak, которая содержит все стили
parent=keycloak

# Импортируем общие ресурсы
import=common/keycloak

# Подключаем ваши скрипты (для капчи)
scripts=js/altcha-import.js

# Подключаем ваши дополнительные стили (если есть)
styles=css/styles.css

# Поддерживаемые локали
locales=en